// cards
const LOAD_CARDS = "GET_CARDS";
const CREATE_CARD = "CREATE_CARD";
const UPDATE_CARD = "UPDATE_CARD";
const DELETE_CARD = "DELETE_CARD";
const FILTER_CARDS = "FILTER_CARDS";
const CLEAR_FILTER = "CLEAR_FILTER";

// users
const LOG_IN = "LOG_IN";
const LOG_OUT = "LOG_OUT";
const CREATE_USER = "CREATE_USER";
const UPDATE_USER = "UPDATE_USER";
const DELETE_USER = "DELETE_USER";

// app
// error of fetching data
const ERROR_DISPLAY_ON = "ERROR_DISPLAY_ON";
const ERROR_DISPLAY_OFF = "ERROR_DISPLAY_OFF";

// loading
const APP_LOADING = "APP_LOADING";

export {
  LOAD_CARDS,
  CREATE_CARD,
  UPDATE_CARD,
  DELETE_CARD,
  FILTER_CARDS,
  CLEAR_FILTER,
  LOG_IN,
  LOG_OUT,
  CREATE_USER,
  UPDATE_USER,
  DELETE_USER,
  ERROR_DISPLAY_ON,
  ERROR_DISPLAY_OFF,
  APP_LOADING,
};
